### ISSUE TITLE
Ukoly serie 2

### ISSUE THREAD

**Issue by starkroman** [starkroman/python-012021#2]
Posílám ti k opravě moje řešení ze série 2. Děkuji předem...

**Comment by pesikj** [comment]
### 6. úkol :heavy_check_mark:

Super, pouze na řádku níže můžeš použít kombinaci apostrofů a uvozovek a nemusíš používat zpětná lomítka.​

```python
print(f'V regionu "{region}" jsou následující státy + hlavní město:')
```

### 7. úkol :heavy_check_mark:
​
Taky super, pouze bych je možné odstranit zpětná lomítka jako výše. :-)
​
### 8. úkol :heavy_check_mark:
​
Program je správně, ale nepoužívej prosím první velké písmeno v názvu funkce. Velké první písmeno je vyhrazeno pro třídy. Jinak super.

```python
def cenaSMSky(text):
```
​
### 9. úkol :heavy_check_mark:

Ve funkci `ohodnotStudenta` měníš zprávu při každém řádku. Navrhuji upravit funkci takto:

- Pokud ​narazíš na pětku, je jasné, že student propadl a funkce může skončit.
- Dále bych přidal pomocnou proměnnou, která ti určuje, zda se tam vyskytuje trojka. Potom na konci můžeš použít tuto pomocnou proměnnou a průměr k rozhodnutí, zda prospěl nebo prospěl s vyznamenáním.
Program ve tvém případě pro zadaná data fungoval správně, ale pokud by Jarka Metelka dostal pětku z matematiky a ne z ekonomiky, tak si při dalším průchodu cyklu přepíšeš "Neprospěl" na "Prospěl", ale to by tak nemělo být.

```python
def ohodnotStudenta(zaznam):
    novySlovnik = {}
    jmeno = ""
    soucet = 0
    zprava = ""
    trojkaAHorsi = False
    for item in zaznam.values():
        if str(item).isdigit():
            soucet += item
            if item >= 3:
                trojkaAHorsi = True
            if item == 5:
                zprava = "Neprospěl"
                novySlovnik[jmeno] += zprava
                return novySlovnik
        else:
            jmeno = item
            novySlovnik[jmeno] = ""
    prumer = soucet / (len(zaznam) - 1)
    if not trojkaAHorsi and prumer <= 1.5:
        zprava = "Prospěl s vyznamenáním"
    else:
        zprava = "Prospěl"
    novySlovnik[jmeno] += zprava
    return novySlovnik

```
​
### 10. úkol :heavy_check_mark:
​
Super
​
Shrnuti + pozadavky na upravu
​
Podívej se prosím na 9. úkol, jestli je ti moje úprava jasná. Je to ale menší chyba a pro zadaná data fungoval program v pořádku, takže ti bod samozřejmě dám. Ostatní příklady jsou správně, takže celkem 5 bodů, dobrá práce. 👍

**Comment by starkroman** [comment]
Děkuji za připomínku. Je to jasné.
