### ISSUE TITLE
Ukoly 4-serie

### ISSUE THREAD

**Issue by starkroman** [starkroman/python-012021#4]
Ahoj Jirko! Prosím o opravu 4serie. Posílám i úlohu 17bonus, ale nějak mi to nešlape a nevím si s tím rady. Budu vděčný za tvoji radu. S těmi úlohami na "Pandas" jsem si s tím trochu hrál mimo zadání, ale to poznáš, že? Jinak úloha 19 a 20 - super. Děkuji za náměty.

P.S.
Makal jsem celou neděli. Uf.

**Comment by pesikj** [comment]
Ahoj Romane,

### Příklad 16

Super

### Příklad 17

Taky super. U té `__init__()` funkce to takto mít můžeš, teoreticky může mít uživatel už něco nakoukáno při vytvoření (např. převod dat z jiného datového souboru).

Funkci `get_delka_sledovani()` v pokročilé variantě asi nemáš dodělanou, ale v podstatě by to byl hodně podobný cyklus jako už tam mám, takže v pohodě :-)

U té metody `get_info()` používáš `self` při práci se seriálem nebo filmem, ale to tam být nemusí. `self` používáme pouze v případě, že třída pracuje s vlastními atributy. Plus je tam `jmeno` namísto `nazev`.

```python

    def get_info(self):
        vystup = f"{self.jmeno} zkouknul tyto pořady:"
        for porad in self.seznamSledovani:
            vystup += porad.nazev + ", jehož žánr je: " + porad.zanr
        return vystup


```

### Příklad 18

Super :-)

### Příklad 19

Tady máš vlastní zadání, ale použil jsi vše, co bylo požadováno, takže super :-)

### Příklad 20

Líbí se mi, že jsi využil ty funkce pro generování části adresy :-)

### Shrnutí

Všechny úkoly jsou správně, u těch posledních dvou sis i upravil zadání, takže zapisuji 5 bodů :-)
