### ISSUE TITLE
Django 8+9

### ISSUE THREAD

**Issue by starkroman** [starkroman/python-012021#8]
Ahoj!

Odevzdal jsem část 8+9 Django. Snad všechno a OK. Děkuji za opravu.

**Comment by pesikj** [comment]
Ahoj Romane,

promiň, že to tak trvalo, ale asi jsi mi zapomněl issue přiřadit a já si ho všiml až v úterý :-)

### Příklad 36

Super :-)

### Příklad 37

Taky super :-)

### Příklad 38

Super, jsem moc rád, že jsi správně pochopil systém fungování URL adres, s tím mají lidi problémy.

### Příklad 39 a 40

Taky super

### Příklad 41

Nastaveno správně

### Příklad 42

Super

### Příklad 43

Taky super

### Příklad 44 a 45

Oba modely jsou správně

### Shrnutí

Vše je splněno perfektně a je vidět, že tomu rozumíš a vybíráš vždy ten správný způsob, jak problém řešit. Připisuji 10 bodů, máš již dostatek bodů na certifikát.
